// Country configuration with phone codes and currencies
export const countryConfig = {
  Afghanistan: { phoneCode: '+93', currency: 'AFN', currencySymbol: '؋' },
  Albania: { phoneCode: '+355', currency: 'ALL', currencySymbol: 'L' },
  Algeria: { phoneCode: '+213', currency: 'DZD', currencySymbol: 'د.ج' },
  Andorra: { phoneCode: '+376', currency: 'EUR', currencySymbol: '€' },
  Angola: { phoneCode: '+244', currency: 'AOA', currencySymbol: 'Kz' },
  'Antigua and Barbuda': {
    phoneCode: '+1-268',
    currency: 'XCD',
    currencySymbol: '$',
  },
  Argentina: { phoneCode: '+54', currency: 'ARS', currencySymbol: '$' },
  Armenia: { phoneCode: '+374', currency: 'AMD', currencySymbol: '֏' },
  Australia: { phoneCode: '+61', currency: 'AUD', currencySymbol: '$' },
  Austria: { phoneCode: '+43', currency: 'EUR', currencySymbol: '€' },
  Azerbaijan: { phoneCode: '+994', currency: 'AZN', currencySymbol: '₼' },
  Bahamas: { phoneCode: '+1-242', currency: 'BSD', currencySymbol: '$' },
  Bahrain: { phoneCode: '+973', currency: 'BHD', currencySymbol: '.د.ب' },
  Bangladesh: { phoneCode: '+880', currency: 'BDT', currencySymbol: '৳' },
  Barbados: { phoneCode: '+1-246', currency: 'BBD', currencySymbol: '$' },
  Belarus: { phoneCode: '+375', currency: 'BYN', currencySymbol: 'Br' },
  Belgium: { phoneCode: '+32', currency: 'EUR', currencySymbol: '€' },
  Belize: { phoneCode: '+501', currency: 'BZD', currencySymbol: '$' },
  Benin: { phoneCode: '+229', currency: 'XOF', currencySymbol: 'CFA' },
  Bhutan: { phoneCode: '+975', currency: 'BTN', currencySymbol: 'Nu.' },
  Bolivia: { phoneCode: '+591', currency: 'BOB', currencySymbol: 'Bs.' },
  'Bosnia and Herzegovina': {
    phoneCode: '+387',
    currency: 'BAM',
    currencySymbol: 'KM',
  },
  Botswana: { phoneCode: '+267', currency: 'BWP', currencySymbol: 'P' },
  Brazil: { phoneCode: '+55', currency: 'BRL', currencySymbol: 'R$' },
  Brunei: { phoneCode: '+673', currency: 'BND', currencySymbol: '$' },
  Bulgaria: { phoneCode: '+359', currency: 'BGN', currencySymbol: 'лв' },
  'Burkina Faso': { phoneCode: '+226', currency: 'XOF', currencySymbol: 'CFA' },
  Burundi: { phoneCode: '+257', currency: 'BIF', currencySymbol: 'FBu' },
  'Cabo Verde': { phoneCode: '+238', currency: 'CVE', currencySymbol: '$' },
  Cambodia: { phoneCode: '+855', currency: 'KHR', currencySymbol: '៛' },
  Cameroon: { phoneCode: '+237', currency: 'XAF', currencySymbol: 'CFA' },
  Canada: { phoneCode: '+1', currency: 'CAD', currencySymbol: '$' },
  'Central African Republic': {
    phoneCode: '+236',
    currency: 'XAF',
    currencySymbol: 'CFA',
  },
  Chad: { phoneCode: '+235', currency: 'XAF', currencySymbol: 'CFA' },
  Chile: { phoneCode: '+56', currency: 'CLP', currencySymbol: '$' },
  China: { phoneCode: '+86', currency: 'CNY', currencySymbol: '¥' },
  Colombia: { phoneCode: '+57', currency: 'COP', currencySymbol: '$' },
  Comoros: { phoneCode: '+269', currency: 'KMF', currencySymbol: 'CF' },
  Congo: { phoneCode: '+242', currency: 'XAF', currencySymbol: 'CFA' },
  'Costa Rica': { phoneCode: '+506', currency: 'CRC', currencySymbol: '₡' },
  Croatia: { phoneCode: '+385', currency: 'HRK', currencySymbol: 'kn' },
  Cuba: { phoneCode: '+53', currency: 'CUP', currencySymbol: '$' },
  Cyprus: { phoneCode: '+357', currency: 'EUR', currencySymbol: '€' },
  'Czech Republic': {
    phoneCode: '+420',
    currency: 'CZK',
    currencySymbol: 'Kč',
  },
  Denmark: { phoneCode: '+45', currency: 'DKK', currencySymbol: 'kr' },
  Djibouti: { phoneCode: '+253', currency: 'DJF', currencySymbol: 'Fdj' },
  Dominica: { phoneCode: '+1-767', currency: 'XCD', currencySymbol: '$' },
  'Dominican Republic': {
    phoneCode: '+1-809',
    currency: 'DOP',
    currencySymbol: '$',
  },
  Ecuador: { phoneCode: '+593', currency: 'USD', currencySymbol: '$' },
  Egypt: { phoneCode: '+20', currency: 'EGP', currencySymbol: '£' },
  'El Salvador': { phoneCode: '+503', currency: 'USD', currencySymbol: '$' },
  'Equatorial Guinea': {
    phoneCode: '+240',
    currency: 'XAF',
    currencySymbol: 'CFA',
  },
  Eritrea: { phoneCode: '+291', currency: 'ERN', currencySymbol: 'Nfk' },
  Estonia: { phoneCode: '+372', currency: 'EUR', currencySymbol: '€' },
  Eswatini: { phoneCode: '+268', currency: 'SZL', currencySymbol: 'L' },
  Ethiopia: { phoneCode: '+251', currency: 'ETB', currencySymbol: 'Br' },
  Fiji: { phoneCode: '+679', currency: 'FJD', currencySymbol: '$' },
  Finland: { phoneCode: '+358', currency: 'EUR', currencySymbol: '€' },
  France: { phoneCode: '+33', currency: 'EUR', currencySymbol: '€' },
  Gabon: { phoneCode: '+241', currency: 'XAF', currencySymbol: 'CFA' },
  Gambia: { phoneCode: '+220', currency: 'GMD', currencySymbol: 'D' },
  Georgia: { phoneCode: '+995', currency: 'GEL', currencySymbol: '₾' },
  Germany: { phoneCode: '+49', currency: 'EUR', currencySymbol: '€' },
  Ghana: { phoneCode: '+233', currency: 'GHS', currencySymbol: '₵' },
  Greece: { phoneCode: '+30', currency: 'EUR', currencySymbol: '€' },
  Grenada: { phoneCode: '+1-473', currency: 'XCD', currencySymbol: '$' },
  Guatemala: { phoneCode: '+502', currency: 'GTQ', currencySymbol: 'Q' },
  Guinea: { phoneCode: '+224', currency: 'GNF', currencySymbol: 'FG' },
  'Guinea-Bissau': {
    phoneCode: '+245',
    currency: 'XOF',
    currencySymbol: 'CFA',
  },
  Guyana: { phoneCode: '+592', currency: 'GYD', currencySymbol: '$' },
  Haiti: { phoneCode: '+509', currency: 'HTG', currencySymbol: 'G' },
  Honduras: { phoneCode: '+504', currency: 'HNL', currencySymbol: 'L' },
  Hungary: { phoneCode: '+36', currency: 'HUF', currencySymbol: 'Ft' },
  Iceland: { phoneCode: '+354', currency: 'ISK', currencySymbol: 'kr' },
  India: { phoneCode: '+91', currency: 'INR', currencySymbol: '₹' },
  Indonesia: { phoneCode: '+62', currency: 'IDR', currencySymbol: 'Rp' },
  Iran: { phoneCode: '+98', currency: 'IRR', currencySymbol: '﷼' },
  Iraq: { phoneCode: '+964', currency: 'IQD', currencySymbol: 'ع.د' },
  Ireland: { phoneCode: '+353', currency: 'EUR', currencySymbol: '€' },
  Israel: { phoneCode: '+972', currency: 'ILS', currencySymbol: '₪' },
  Italy: { phoneCode: '+39', currency: 'EUR', currencySymbol: '€' },
  Jamaica: { phoneCode: '+1-876', currency: 'JMD', currencySymbol: '$' },
  Japan: { phoneCode: '+81', currency: 'JPY', currencySymbol: '¥' },
  Jordan: { phoneCode: '+962', currency: 'JOD', currencySymbol: 'د.ا' },
  Kazakhstan: { phoneCode: '+7', currency: 'KZT', currencySymbol: '₸' },
  Kenya: { phoneCode: '+254', currency: 'KES', currencySymbol: 'KSh' },
  Kiribati: { phoneCode: '+686', currency: 'AUD', currencySymbol: '$' },
  Kosovo: { phoneCode: '+383', currency: 'EUR', currencySymbol: '€' },
  Kuwait: { phoneCode: '+965', currency: 'KWD', currencySymbol: 'د.ك' },
  Kyrgyzstan: { phoneCode: '+996', currency: 'KGS', currencySymbol: 'с' },
  Laos: { phoneCode: '+856', currency: 'LAK', currencySymbol: '₭' },
  Latvia: { phoneCode: '+371', currency: 'EUR', currencySymbol: '€' },
  Lebanon: { phoneCode: '+961', currency: 'LBP', currencySymbol: 'ل.ل' },
  Lesotho: { phoneCode: '+266', currency: 'LSL', currencySymbol: 'L' },
  Liberia: { phoneCode: '+231', currency: 'LRD', currencySymbol: '$' },
  Libya: { phoneCode: '+218', currency: 'LYD', currencySymbol: 'ل.د' },
  Liechtenstein: { phoneCode: '+423', currency: 'CHF', currencySymbol: 'CHF' },
  Lithuania: { phoneCode: '+370', currency: 'EUR', currencySymbol: '€' },
  Luxembourg: { phoneCode: '+352', currency: 'EUR', currencySymbol: '€' },
  Madagascar: { phoneCode: '+261', currency: 'MGA', currencySymbol: 'Ar' },
  Malawi: { phoneCode: '+265', currency: 'MWK', currencySymbol: 'MK' },
  Malaysia: { phoneCode: '+60', currency: 'MYR', currencySymbol: 'RM' },
  Maldives: { phoneCode: '+960', currency: 'MVR', currencySymbol: 'Rf' },
  Mali: { phoneCode: '+223', currency: 'XOF', currencySymbol: 'CFA' },
  Malta: { phoneCode: '+356', currency: 'EUR', currencySymbol: '€' },
  'Marshall Islands': {
    phoneCode: '+692',
    currency: 'USD',
    currencySymbol: '$',
  },
  Mauritania: { phoneCode: '+222', currency: 'MRU', currencySymbol: 'UM' },
  Mauritius: { phoneCode: '+230', currency: 'MUR', currencySymbol: '₨' },
  Mexico: { phoneCode: '+52', currency: 'MXN', currencySymbol: '$' },
  Micronesia: { phoneCode: '+691', currency: 'USD', currencySymbol: '$' },
  Moldova: { phoneCode: '+373', currency: 'MDL', currencySymbol: 'L' },
  Monaco: { phoneCode: '+377', currency: 'EUR', currencySymbol: '€' },
  Mongolia: { phoneCode: '+976', currency: 'MNT', currencySymbol: '₮' },
  Montenegro: { phoneCode: '+382', currency: 'EUR', currencySymbol: '€' },
  Morocco: { phoneCode: '+212', currency: 'MAD', currencySymbol: 'د.م.' },
  Mozambique: { phoneCode: '+258', currency: 'MZN', currencySymbol: 'MT' },
  Myanmar: { phoneCode: '+95', currency: 'MMK', currencySymbol: 'K' },
  Namibia: { phoneCode: '+264', currency: 'NAD', currencySymbol: '$' },
  Nauru: { phoneCode: '+674', currency: 'AUD', currencySymbol: '$' },
  Nepal: { phoneCode: '+977', currency: 'NPR', currencySymbol: '₨' },
  Netherlands: { phoneCode: '+31', currency: 'EUR', currencySymbol: '€' },
  'New Zealand': { phoneCode: '+64', currency: 'NZD', currencySymbol: '$' },
  Nicaragua: { phoneCode: '+505', currency: 'NIO', currencySymbol: 'C$' },
  Niger: { phoneCode: '+227', currency: 'XOF', currencySymbol: 'CFA' },
  Nigeria: { phoneCode: '+234', currency: 'NGN', currencySymbol: '₦' },
  'North Korea': { phoneCode: '+850', currency: 'KPW', currencySymbol: '₩' },
  'North Macedonia': {
    phoneCode: '+389',
    currency: 'MKD',
    currencySymbol: 'ден',
  },
  Norway: { phoneCode: '+47', currency: 'NOK', currencySymbol: 'kr' },
  Oman: { phoneCode: '+968', currency: 'OMR', currencySymbol: 'ر.ع.' },
  Pakistan: { phoneCode: '+92', currency: 'PKR', currencySymbol: '₨' },
  Palau: { phoneCode: '+680', currency: 'USD', currencySymbol: '$' },
  Palestine: { phoneCode: '+970', currency: 'ILS', currencySymbol: '₪' },
  Panama: { phoneCode: '+507', currency: 'USD', currencySymbol: '$' },
  'Papua New Guinea': {
    phoneCode: '+675',
    currency: 'PGK',
    currencySymbol: 'K',
  },
  Paraguay: { phoneCode: '+595', currency: 'PYG', currencySymbol: '₲' },
  Peru: { phoneCode: '+51', currency: 'PEN', currencySymbol: 'S/' },
  Philippines: { phoneCode: '+63', currency: 'PHP', currencySymbol: '₱' },
  Poland: { phoneCode: '+48', currency: 'PLN', currencySymbol: 'zł' },
  Portugal: { phoneCode: '+351', currency: 'EUR', currencySymbol: '€' },
  Qatar: { phoneCode: '+974', currency: 'QAR', currencySymbol: 'ر.ق' },
  Romania: { phoneCode: '+40', currency: 'RON', currencySymbol: 'lei' },
  Russia: { phoneCode: '+7', currency: 'RUB', currencySymbol: '₽' },
  Rwanda: { phoneCode: '+250', currency: 'RWF', currencySymbol: 'FRw' },
  'Saint Kitts and Nevis': {
    phoneCode: '+1-869',
    currency: 'XCD',
    currencySymbol: '$',
  },
  'Saint Lucia': { phoneCode: '+1-758', currency: 'XCD', currencySymbol: '$' },
  'Saint Vincent and the Grenadines': {
    phoneCode: '+1-784',
    currency: 'XCD',
    currencySymbol: '$',
  },
  Samoa: { phoneCode: '+685', currency: 'WST', currencySymbol: 'T' },
  'San Marino': { phoneCode: '+378', currency: 'EUR', currencySymbol: '€' },
  'Sao Tome and Principe': {
    phoneCode: '+239',
    currency: 'STN',
    currencySymbol: 'Db',
  },
  'Saudi Arabia': { phoneCode: '+966', currency: 'SAR', currencySymbol: 'ر.س' },
  Senegal: { phoneCode: '+221', currency: 'XOF', currencySymbol: 'CFA' },
  Serbia: { phoneCode: '+381', currency: 'RSD', currencySymbol: 'дин' },
  Seychelles: { phoneCode: '+248', currency: 'SCR', currencySymbol: '₨' },
  'Sierra Leone': { phoneCode: '+232', currency: 'SLL', currencySymbol: 'Le' },
  Singapore: { phoneCode: '+65', currency: 'SGD', currencySymbol: '$' },
  Slovakia: { phoneCode: '+421', currency: 'EUR', currencySymbol: '€' },
  Slovenia: { phoneCode: '+386', currency: 'EUR', currencySymbol: '€' },
  'Solomon Islands': {
    phoneCode: '+677',
    currency: 'SBD',
    currencySymbol: '$',
  },
  Somalia: { phoneCode: '+252', currency: 'SOS', currencySymbol: 'Sh' },
  'South Africa': { phoneCode: '+27', currency: 'ZAR', currencySymbol: 'R' },
  'South Korea': { phoneCode: '+82', currency: 'KRW', currencySymbol: '₩' },
  'South Sudan': { phoneCode: '+211', currency: 'SSP', currencySymbol: '£' },
  Spain: { phoneCode: '+34', currency: 'EUR', currencySymbol: '€' },
  'Sri Lanka': { phoneCode: '+94', currency: 'LKR', currencySymbol: '₨' },
  Sudan: { phoneCode: '+249', currency: 'SDG', currencySymbol: 'ج.س.' },
  Suriname: { phoneCode: '+597', currency: 'SRD', currencySymbol: '$' },
  Sweden: { phoneCode: '+46', currency: 'SEK', currencySymbol: 'kr' },
  Switzerland: { phoneCode: '+41', currency: 'CHF', currencySymbol: 'CHF' },
  Syria: { phoneCode: '+963', currency: 'SYP', currencySymbol: '£' },
  Taiwan: { phoneCode: '+886', currency: 'TWD', currencySymbol: 'NT$' },
  Tajikistan: { phoneCode: '+992', currency: 'TJS', currencySymbol: 'ЅМ' },
  Tanzania: { phoneCode: '+255', currency: 'TZS', currencySymbol: 'TSh' },
  Thailand: { phoneCode: '+66', currency: 'THB', currencySymbol: '฿' },
  'Timor-Leste': { phoneCode: '+670', currency: 'USD', currencySymbol: '$' },
  Togo: { phoneCode: '+228', currency: 'XOF', currencySymbol: 'CFA' },
  Tonga: { phoneCode: '+676', currency: 'TOP', currencySymbol: 'T$' },
  'Trinidad and Tobago': {
    phoneCode: '+1-868',
    currency: 'TTD',
    currencySymbol: '$',
  },
  Tunisia: { phoneCode: '+216', currency: 'TND', currencySymbol: 'د.ت' },
  Turkey: { phoneCode: '+90', currency: 'TRY', currencySymbol: '₺' },
  Turkmenistan: { phoneCode: '+993', currency: 'TMT', currencySymbol: 'm' },
  Tuvalu: { phoneCode: '+688', currency: 'AUD', currencySymbol: '$' },
  Uganda: { phoneCode: '+256', currency: 'UGX', currencySymbol: 'USh' },
  Ukraine: { phoneCode: '+380', currency: 'UAH', currencySymbol: '₴' },
  'United Arab Emirates': {
    phoneCode: '+971',
    currency: 'AED',
    currencySymbol: 'د.إ',
  },
  'United Kingdom': { phoneCode: '+44', currency: 'GBP', currencySymbol: '£' },
  'United States': { phoneCode: '+1', currency: 'USD', currencySymbol: '$' },
  Uruguay: { phoneCode: '+598', currency: 'UYU', currencySymbol: '$' },
  Uzbekistan: { phoneCode: '+998', currency: 'UZS', currencySymbol: 'лв' },
  Vanuatu: { phoneCode: '+678', currency: 'VUV', currencySymbol: 'Vt' },
  'Vatican City': { phoneCode: '+379', currency: 'EUR', currencySymbol: '€' },
  Venezuela: { phoneCode: '+58', currency: 'VES', currencySymbol: 'Bs.' },
  Vietnam: { phoneCode: '+84', currency: 'VND', currencySymbol: '₫' },
  Yemen: { phoneCode: '+967', currency: 'YER', currencySymbol: '﷼' },
  Zambia: { phoneCode: '+260', currency: 'ZMW', currencySymbol: 'ZK' },
  Zimbabwe: { phoneCode: '+263', currency: 'ZWL', currencySymbol: '$' },
};
